/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Compass: typeof import('./src/components/Compass.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    FligntControlStatus: typeof import('./src/components/FligntControlStatus.vue')['default']
    GPSData: typeof import('./src/components/GPSData.vue')['default']
    Model3d: typeof import('./src/components/model3d.vue')['default']
    Receiver: typeof import('./src/components/Receiver.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SenserData: typeof import('./src/components/SenserData.vue')['default']
    Wave: typeof import('./src/components/Wave.vue')['default']
    Waves: typeof import('./src/components/Waves.vue')['default']
  }
}
